OpenSonATA Source Code Documentation
Back to setiCode Home
opensonata.dataDisplays.ReadoutPlot Class Reference
Classes
class ReadoutMouseListener
Public Member Functions
ReadoutPlot ()
void addReadoutListener (ReadoutListener listener)
void removeReadoutListener (ReadoutListener listener)
Private Member Functions
synchronized void _readout (int x, int y)
void _notifyListeners (double xValue, double yValue)
Private Attributes
Vector _readoutListeners = null
Detailed Description
This extension of Plot permits interactive readout of xvalue, yvalue positions on the plot. Mouse motion over the plot calls the registered ReadoutListeners, giving them the position information.
To be notified when this occurs, create an object that implements the ReadoutListener interface and add that listener using addReadoutListener().
Definition at line 100 of file ReadoutPlot.java.
Constructor & Destructor Documentation
opensonata.dataDisplays.ReadoutPlot.ReadoutPlot ()
Constructor.
Definition at line 106 of file ReadoutPlot.java.
Member Function Documentation
void opensonata.dataDisplays.ReadoutPlot._notifyListeners (double xValue, double yValue) [private]
Notify all edit listeners that have registered.
Parameters:
xValue the x pixel position in the graph.
yValue the y pixel position in the graph.
Definition at line 188 of file ReadoutPlot.java.
References opensonata.dataDisplays.ReadoutPlot._readoutListeners.
Referenced by opensonata.dataDisplays.ReadoutPlot._readout().
synchronized void opensonata.dataDisplays.ReadoutPlot._readout (int x, int y) [private]
Readout the given position. Convert to xvalue, yvalue and send the result to the registered readout listeners.
Parameters:
x the x pixel position in the graph.
y the y pixel position in the graph.
Definition at line 159 of file ReadoutPlot.java.
References opensonata.dataDisplays.ReadoutPlot._notifyListeners().
void opensonata.dataDisplays.ReadoutPlot.addReadoutListener (ReadoutListener listener)
Add a listener to be informed when the user modifies a data set.
Parameters:
listener The listener.
See also:
ReadoutListener
Definition at line 118 of file ReadoutPlot.java.
References opensonata.dataDisplays.ReadoutPlot._readoutListeners.
Referenced by opensonata.dataDisplays.WaterfallDisplay.createCompAmpTimeAvgPlot(), and opensonata.dataDisplays.BaselineDisplay.init().
void opensonata.dataDisplays.ReadoutPlot.removeReadoutListener (ReadoutListener listener)
Unregister a readout listener. If the specified listener has not been previously registered, then do nothing.
Parameters:
listener The listener to remove from the list of listeners to which edit events are sent.
Definition at line 142 of file ReadoutPlot.java.
References opensonata.dataDisplays.ReadoutPlot._readoutListeners.
Member Data Documentation
Vector opensonata.dataDisplays.ReadoutPlot._readoutListeners = null [private]
Edit listeners.
Definition at line 207 of file ReadoutPlot.java.
Referenced by opensonata.dataDisplays.ReadoutPlot._notifyListeners(), opensonata.dataDisplays.ReadoutPlot.addReadoutListener(), and opensonata.dataDisplays.ReadoutPlot.removeReadoutListener().
The documentation for this class was generated from the following file:
ReadoutPlot.java