OpenSonATA Source Code Documentation
Back to setiCode Home
opensonata.dataDisplays.WaterfallDisplay.CoefConversion Class Reference
Public Member Functions
synchronized void startNewDataStream ()
double[] convertCoefsTo2HzFreqValues (double coef[])
double[] convertCoefsTo4HzFreqValues (double coef[])
synchronized double[] convertCoefsTo1HzFreqValues (double newCoef[])
void convertFFTValuesToPixels (double coef[], int[] pixbuff)
Private Member Functions
void convertCoefsToFreqValues (double coef[])
Private Attributes
double[] prevCoef = null
Detailed Description
Converts complex amplitude time samples into 1,2 or 4 Hz data and converts the freq domain values to pixels. Note that the cofficients arrive in half frames. So 512 samples at a time, 1024 values which are real,imaginary,real,imaginary... One full frame is 1024 samples, which is 2048 values (real,imaginary,real,imaginary...)
Definition at line 238 of file WaterfallDisplay.java.
Member Function Documentation
synchronized double [] opensonata.dataDisplays.WaterfallDisplay.CoefConversion.convertCoefsTo1HzFreqValues (double newCoef[])
Convert the 1Hz complex amplitude values to frequency values. This pieces together the last half frame and the current half frame to operate on one full frame. Pipelined.
Parameters:
newCoef the latest half frame.
Returns:
an array of frequency values. Sonce this is pipelined, the first time there is no half frame of coeffiecients stored so a zeroed array is returned.
Definition at line 312 of file WaterfallDisplay.java.
References opensonata.dataDisplays.WaterfallDisplay.CoefConversion.convertCoefsToFreqValues(), and opensonata.dataDisplays.WaterfallDisplay.CoefConversion.prevCoef.
double [] opensonata.dataDisplays.WaterfallDisplay.CoefConversion.convertCoefsTo2HzFreqValues (double coef[])
Convert the 1kHz data to 2kHz values.
Parameters:
coef the array of coefficients. This is a half frame of coefficients.
Definition at line 262 of file WaterfallDisplay.java.
References opensonata.dataDisplays.WaterfallDisplay.CoefConversion.convertCoefsToFreqValues().
double [] opensonata.dataDisplays.WaterfallDisplay.CoefConversion.convertCoefsTo4HzFreqValues (double coef[])
Convert the 1kHz data to 4kHz values.
Todo:
Is this the algorithm correct?
Parameters:
coef the array of coefficients. This is a half frame of coefficients.
Definition at line 284 of file WaterfallDisplay.java.
References opensonata.dataDisplays.WaterfallDisplay.CoefConversion.convertCoefsToFreqValues().
void opensonata.dataDisplays.WaterfallDisplay.CoefConversion.convertCoefsToFreqValues (double coef[]) [private]
Convert the complex amplitude time samples to the frequency domain.
Time sample order is real, imag in adjacent array elements
Parameters:
coef the array of complex amplitude time samples. The return values are placed back into the coef[] array.
Definition at line 376 of file WaterfallDisplay.java.
Referenced by opensonata.dataDisplays.WaterfallDisplay.CoefConversion.convertCoefsTo1HzFreqValues(), opensonata.dataDisplays.WaterfallDisplay.CoefConversion.convertCoefsTo2HzFreqValues(), and opensonata.dataDisplays.WaterfallDisplay.CoefConversion.convertCoefsTo4HzFreqValues().
void opensonata.dataDisplays.WaterfallDisplay.CoefConversion.convertFFTValuesToPixels (double coef[], int[] pixbuff)
Convert the FFT values to pixel values.
Todo:
kes: we need to eliminate the edge bins created by the oversampling process; they are discarded because they lie outside the actual bandwidth of the subchannel.
Parameters:
coef the array of FFTp coeffieients.
pixbuff the output pixels.
Definition at line 430 of file WaterfallDisplay.java.
synchronized void opensonata.dataDisplays.WaterfallDisplay.CoefConversion.startNewDataStream ()
Initialze the previous conversions coefficients.
Definition at line 250 of file WaterfallDisplay.java.
References opensonata.dataDisplays.WaterfallDisplay.CoefConversion.prevCoef.
Member Data Documentation
double [] opensonata.dataDisplays.WaterfallDisplay.CoefConversion.prevCoef = null [private]
Storage of the previous conversions coefficients. coefficients arrive in half frames.
Definition at line 245 of file WaterfallDisplay.java.
Referenced by opensonata.dataDisplays.WaterfallDisplay.CoefConversion.convertCoefsTo1HzFreqValues(), and opensonata.dataDisplays.WaterfallDisplay.CoefConversion.startNewDataStream().
The documentation for this class was generated from the following file:
WaterfallDisplay.java