OpenSonATA Source Code Documentation
Back to setiCode Home
opensonata.dataDisplays.WaterfallDisplay.WaterfallCmdLineOptions Class Reference
Public Member Functions
WaterfallCmdLineOptions ()
String getInFilename ()
String getOutFilename ()
int getResolutionHz ()
int getXpos ()
int getYpos ()
int getSubbandOffset ()
boolean getSlowPlay ()
boolean getRepeatPlay ()
boolean getBatch ()
String getTitle ()
boolean parseCommandLineArgs (String[] args)
Detailed Description
Process the command line options.
Definition at line 2475 of file WaterfallDisplay.java.
Constructor & Destructor Documentation
opensonata.dataDisplays.WaterfallDisplay.WaterfallCmdLineOptions.WaterfallCmdLineOptions ()
Constructor.
Definition at line 2492 of file WaterfallDisplay.java.
Member Function Documentation
boolean opensonata.dataDisplays.WaterfallDisplay.WaterfallCmdLineOptions.getBatch ()
Get the batch flag.
Returns:
true if batch should be performed, false if not.
Definition at line 2591 of file WaterfallDisplay.java.
Referenced by opensonata.dataDisplays.WaterfallDisplay.main().
String opensonata.dataDisplays.WaterfallDisplay.WaterfallCmdLineOptions.getInFilename ()
Get the input file name.
Returns:
the input file name.
Definition at line 2511 of file WaterfallDisplay.java.
Referenced by opensonata.dataDisplays.WaterfallDisplay.main().
String opensonata.dataDisplays.WaterfallDisplay.WaterfallCmdLineOptions.getOutFilename ()
Get the output file name.
Returns:
the output file name.
Definition at line 2521 of file WaterfallDisplay.java.
Referenced by opensonata.dataDisplays.WaterfallDisplay.main().
boolean opensonata.dataDisplays.WaterfallDisplay.WaterfallCmdLineOptions.getRepeatPlay ()
Get the repeat play flag.
Returns:
true if repeat play should be performed, false if not.
Definition at line 2581 of file WaterfallDisplay.java.
Referenced by opensonata.dataDisplays.WaterfallDisplay.main().
int opensonata.dataDisplays.WaterfallDisplay.WaterfallCmdLineOptions.getResolutionHz ()
Get the resolution in Hertz.
Returns:
the resolution in Hertz.
Definition at line 2531 of file WaterfallDisplay.java.
Referenced by opensonata.dataDisplays.WaterfallDisplay.main().
boolean opensonata.dataDisplays.WaterfallDisplay.WaterfallCmdLineOptions.getSlowPlay ()
Get the slow play flag.
Returns:
true if slow play should be performed, false if not.
Definition at line 2571 of file WaterfallDisplay.java.
Referenced by opensonata.dataDisplays.WaterfallDisplay.main().
int opensonata.dataDisplays.WaterfallDisplay.WaterfallCmdLineOptions.getSubbandOffset ()
Get the subband offset.
Returns:
the subband offset.
Definition at line 2561 of file WaterfallDisplay.java.
Referenced by opensonata.dataDisplays.WaterfallDisplay.main().
String opensonata.dataDisplays.WaterfallDisplay.WaterfallCmdLineOptions.getTitle ()
Get the title of the frame.
Returns:
the title of the frame.
Definition at line 2601 of file WaterfallDisplay.java.
Referenced by opensonata.dataDisplays.WaterfallDisplay.main().
int opensonata.dataDisplays.WaterfallDisplay.WaterfallCmdLineOptions.getXpos ()
Get the X position.
Returns:
the X position.
Definition at line 2541 of file WaterfallDisplay.java.
Referenced by opensonata.dataDisplays.WaterfallDisplay.main().
int opensonata.dataDisplays.WaterfallDisplay.WaterfallCmdLineOptions.getYpos ()
Get the Y position.
Returns:
the Y position.
Definition at line 2551 of file WaterfallDisplay.java.
Referenced by opensonata.dataDisplays.WaterfallDisplay.main().
boolean opensonata.dataDisplays.WaterfallDisplay.WaterfallCmdLineOptions.parseCommandLineArgs (String[] args)
Parse the command line paramters.
Parameters:
args the array of command line argument strings.
Returns:
true if arguments are read in with no errors. false if there are errors.
Definition at line 2613 of file WaterfallDisplay.java.
Referenced by opensonata.dataDisplays.WaterfallDisplay.main().
The documentation for this class was generated from the following file:
WaterfallDisplay.java