OpenSonATA Source Code Documentation
Back to setiCode Home
opensonata.dataDisplays.BaselineDisplay.BaselineCmdLineOptions Class Reference
Public Member Functions
BaselineCmdLineOptions ()
String getFilename ()
int getXpos ()
int getYpos ()
int getWidth ()
int getHeight ()
boolean getSlowPlay ()
boolean getTimeAvg ()
boolean parseCommandLineArgs (String[] args)
Detailed Description
Process the command line options.
Definition at line 1397 of file BaselineDisplay.java.
Constructor & Destructor Documentation
opensonata.dataDisplays.BaselineDisplay.BaselineCmdLineOptions.BaselineCmdLineOptions ()
Constructor.
Definition at line 1411 of file BaselineDisplay.java.
Member Function Documentation
String opensonata.dataDisplays.BaselineDisplay.BaselineCmdLineOptions.getFilename ()
Get the input file name.
Returns:
the input file name.
Definition at line 1427 of file BaselineDisplay.java.
Referenced by opensonata.dataDisplays.BaselineDisplay.main().
int opensonata.dataDisplays.BaselineDisplay.BaselineCmdLineOptions.getHeight ()
Get the height.
Returns:
the width.
Definition at line 1467 of file BaselineDisplay.java.
Referenced by opensonata.dataDisplays.BaselineDisplay.main().
boolean opensonata.dataDisplays.BaselineDisplay.BaselineCmdLineOptions.getSlowPlay ()
Get the slow play flag.
Returns:
true if slow play should be performed, false if not.
Definition at line 1477 of file BaselineDisplay.java.
Referenced by opensonata.dataDisplays.BaselineDisplay.main().
boolean opensonata.dataDisplays.BaselineDisplay.BaselineCmdLineOptions.getTimeAvg ()
Get the time average flag.
Returns:
true if time averaging should be performed, false if not.
Definition at line 1487 of file BaselineDisplay.java.
Referenced by opensonata.dataDisplays.BaselineDisplay.main().
int opensonata.dataDisplays.BaselineDisplay.BaselineCmdLineOptions.getWidth ()
Get the width.
Returns:
the width.
Definition at line 1457 of file BaselineDisplay.java.
Referenced by opensonata.dataDisplays.BaselineDisplay.main().
int opensonata.dataDisplays.BaselineDisplay.BaselineCmdLineOptions.getXpos ()
Get the X position.
Returns:
the X position.
Definition at line 1437 of file BaselineDisplay.java.
Referenced by opensonata.dataDisplays.BaselineDisplay.main().
int opensonata.dataDisplays.BaselineDisplay.BaselineCmdLineOptions.getYpos ()
Get the Y position.
Returns:
the Y position.
Definition at line 1447 of file BaselineDisplay.java.
Referenced by opensonata.dataDisplays.BaselineDisplay.main().
boolean opensonata.dataDisplays.BaselineDisplay.BaselineCmdLineOptions.parseCommandLineArgs (String[] args)
Parse the command line paramters.
Parameters:
args the array of command line argument strings.
Returns:
true if arguments are read in with no errors. false if there are errors.
Definition at line 1499 of file BaselineDisplay.java.
Referenced by opensonata.dataDisplays.BaselineDisplay.main().
The documentation for this class was generated from the following file:
BaselineDisplay.java