OpenSonATA Source Code Documentation
Back to setiCode Home
opensonata.dataDisplays.WaterfallDisplay.ComplexAmplitudes Class Reference
Public Member Functions
void setSubbandOffset (int subbandOffset)
void readSubbandData (DataInputStream in) throws java.io.IOException
void skipSubbandData (DataInputStream in) throws java.io.IOException
void read (DataInputStream in) throws java.io.IOException
String getPolAsString ()
void printHeader ()
void printBody ()
Package Attributes
double coef []
Private Member Functions
void unpackCoefsIntoDoubles ()
void readHeader (DataInputStream in) throws java.io.IOException
String polIntToString (int pol)
Detailed Description
Manages complex amplitudes.
See ssePdmInterface.h for the C++ version of this struct (ComplexAmplitudeHeader and SubbandCoef1KHz structs).
Definition at line 497 of file WaterfallDisplay.java.
Member Function Documentation
String opensonata.dataDisplays.WaterfallDisplay.ComplexAmplitudes.getPolAsString ()
get the latest read in polarization from the header as a string.
Returns:
R, L, B, M, or ?
Definition at line 727 of file WaterfallDisplay.java.
References opensonata.dataDisplays.WaterfallDisplay.ComplexAmplitudes.polIntToString().
Referenced by opensonata.dataDisplays.WaterfallDisplay.FileScanner.updateDisplayHeaders().
String opensonata.dataDisplays.WaterfallDisplay.ComplexAmplitudes.polIntToString (int pol) [private]
Convert the polarization value in the header to a string.
Parameters:
pol the polarization number from the header.
Returns:
R, L, B, M, or ?
Definition at line 702 of file WaterfallDisplay.java.
Referenced by opensonata.dataDisplays.WaterfallDisplay.ComplexAmplitudes.getPolAsString(), and opensonata.dataDisplays.WaterfallDisplay.ComplexAmplitudes.printHeader().
void opensonata.dataDisplays.WaterfallDisplay.ComplexAmplitudes.printBody ()
Print to standard out the latest read in complex amplitude values.
Definition at line 755 of file WaterfallDisplay.java.
References opensonata.dataDisplays.WaterfallDisplay.ComplexAmplitudes.coef.
void opensonata.dataDisplays.WaterfallDisplay.ComplexAmplitudes.printHeader ()
Print to standard out the lastest read in header information.
Definition at line 736 of file WaterfallDisplay.java.
References opensonata.dataDisplays.WaterfallDisplay.ComplexAmplitudes.polIntToString().
void opensonata.dataDisplays.WaterfallDisplay.ComplexAmplitudes.read (DataInputStream in) throws java.io.IOException
Manage reading in one full record of header and data.
Parameters:
in the input data stream to read from.
Exceptions:
java.io.IOException.
Definition at line 645 of file WaterfallDisplay.java.
References opensonata.dataDisplays.WaterfallDisplay.ComplexAmplitudes.readHeader(), opensonata.dataDisplays.WaterfallDisplay.ComplexAmplitudes.readSubbandData(), and opensonata.dataDisplays.WaterfallDisplay.ComplexAmplitudes.skipSubbandData().
void opensonata.dataDisplays.WaterfallDisplay.ComplexAmplitudes.readHeader (DataInputStream in) throws java.io.IOException [private]
Read the data header.
Parameters:
in the input data stream to read from.
Exceptions:
java.io.IOException.
Definition at line 562 of file WaterfallDisplay.java.
Referenced by opensonata.dataDisplays.WaterfallDisplay.ComplexAmplitudes.read().
void opensonata.dataDisplays.WaterfallDisplay.ComplexAmplitudes.readSubbandData (DataInputStream in) throws java.io.IOException
Read one half frame of data.
Parameters:
in the input data stream to read from.
Exceptions:
java.io.IOException.
Definition at line 604 of file WaterfallDisplay.java.
References opensonata.dataDisplays.WaterfallDisplay.ComplexAmplitudes.unpackCoefsIntoDoubles().
Referenced by opensonata.dataDisplays.WaterfallDisplay.ComplexAmplitudes.read().
void opensonata.dataDisplays.WaterfallDisplay.ComplexAmplitudes.setSubbandOffset (int subbandOffset)
Set the subband offset for reading the correct subband from the data.
Parameters:
subbandOffset the offset from the subband.
Definition at line 593 of file WaterfallDisplay.java.
Referenced by opensonata.dataDisplays.WaterfallDisplay.WaterfallDisplay().
void opensonata.dataDisplays.WaterfallDisplay.ComplexAmplitudes.skipSubbandData (DataInputStream in) throws java.io.IOException
Read one half frame of data and throw the data away.
Parameters:
in the input data stream to read from.
Exceptions:
java.io.IOException.
Definition at line 627 of file WaterfallDisplay.java.
Referenced by opensonata.dataDisplays.WaterfallDisplay.ComplexAmplitudes.read().
void opensonata.dataDisplays.WaterfallDisplay.ComplexAmplitudes.unpackCoefsIntoDoubles () [private]
Pull out two 4-bit coef values & store in double array. Real, imaginary values are stored in adjacent array elements The result is stored in the coek[] array.
Definition at line 532 of file WaterfallDisplay.java.
References opensonata.dataDisplays.WaterfallDisplay.ComplexAmplitudes.coef.
Referenced by opensonata.dataDisplays.WaterfallDisplay.ComplexAmplitudes.readSubbandData().
Member Data Documentation
double opensonata.dataDisplays.WaterfallDisplay.ComplexAmplitudes.coef[] [package]
Stores the complex values when converted to doubles. RRRRIIII real & image complex pair
4 bit signed (2's complement), high bits on the left extracted coefs as doubles
Definition at line 525 of file WaterfallDisplay.java.
Referenced by opensonata.dataDisplays.WaterfallDisplay.ComplexAmplitudes.printBody(), and opensonata.dataDisplays.WaterfallDisplay.ComplexAmplitudes.unpackCoefsIntoDoubles().
The documentation for this class was generated from the following file:
WaterfallDisplay.java