OpenSonATA Source Code Documentation
Back to setiCode Home
opensonata.dataDisplays.WaterfallDisplay.FileScanner Class Reference
Public Member Functions
void openNewFile (String filename)
void run ()
Package Functions
FileScanner (String filename, int width, int height)
Private Member Functions
void openFile ()
void sleep ()
void separatePreviouslyDisplayedData ()
void addRowsOfConstantBrightness (int brightnessPixelValue, int nRows)
void addPixelRowToImage (int[] pixrow)
void updateDisplayHeaders (ComplexAmplitudes compAmps)
void plotAverageComplexAmplitudes (double[] fftValues)
void plotComplexAmplitudes (double[] values)
void clearPlot ()
void slowPlaySleep ()
void saveWaterfallAsJpegFile () throws java.io.IOException
Detailed Description
Read a file containing gray pixel data or complex amplitude data and turn it into an image.
If an EOFException is received, it means the file has been truncated and it needs to be reopened.
Effectively does a 'tail -f' on the file, sleeping periodically until new data appears.
Definition at line 915 of file WaterfallDisplay.java.
Constructor & Destructor Documentation
opensonata.dataDisplays.WaterfallDisplay.FileScanner.FileScanner (String filename, int width, int height) [package]
Constructor.
Parameters:
filename the name of the file to read.
width the width of the image.
height the height of the image.
Definition at line 936 of file WaterfallDisplay.java.
Member Function Documentation
void opensonata.dataDisplays.WaterfallDisplay.FileScanner.addPixelRowToImage (int[] pixrow) [private]
Add the row of pixels to the top of the image.
Parameters:
pixrow an array of data to be added as one row of the image.
Definition at line 1077 of file WaterfallDisplay.java.
References opensonata.dataDisplays.WaterfallDisplay.redrawImage().
Referenced by opensonata.dataDisplays.WaterfallDisplay.FileScanner.addRowsOfConstantBrightness(), and opensonata.dataDisplays.WaterfallDisplay.FileScanner.run().
void opensonata.dataDisplays.WaterfallDisplay.FileScanner.addRowsOfConstantBrightness (int brightnessPixelValue, int nRows) [private]
Add one or more rows to the image of a constant brightness.
Parameters:
brightnessPixelValue the brighness of the pixel, 0 to 255.
nRows the number of rows to add.
Definition at line 1053 of file WaterfallDisplay.java.
References opensonata.dataDisplays.WaterfallDisplay.FileScanner.addPixelRowToImage(), and opensonata.dataDisplays.WaterfallDisplay.redrawImage().
Referenced by opensonata.dataDisplays.WaterfallDisplay.FileScanner.separatePreviouslyDisplayedData(), and opensonata.dataDisplays.WaterfallDisplay.FileScanner.updateDisplayHeaders().
void opensonata.dataDisplays.WaterfallDisplay.FileScanner.clearPlot () [private]
Clear the plot.
Definition at line 1262 of file WaterfallDisplay.java.
Referenced by opensonata.dataDisplays.WaterfallDisplay.FileScanner.openFile(), and opensonata.dataDisplays.WaterfallDisplay.FileScanner.plotComplexAmplitudes().
void opensonata.dataDisplays.WaterfallDisplay.FileScanner.openFile () [private]
Open the file.
Definition at line 974 of file WaterfallDisplay.java.
References opensonata.dataDisplays.WaterfallDisplay.FileScanner.clearPlot(), and opensonata.dataDisplays.WaterfallDisplay.FileScanner.separatePreviouslyDisplayedData().
Referenced by opensonata.dataDisplays.WaterfallDisplay.FileScanner.openNewFile(), and opensonata.dataDisplays.WaterfallDisplay.FileScanner.run().
void opensonata.dataDisplays.WaterfallDisplay.FileScanner.openNewFile (String filename)
Assign the filename to this class instance and open the file.
Parameters:
filename the name of the file to open.
Definition at line 965 of file WaterfallDisplay.java.
References opensonata.dataDisplays.WaterfallDisplay.FileScanner.openFile().
void opensonata.dataDisplays.WaterfallDisplay.FileScanner.plotAverageComplexAmplitudes (double[] fftValues) [private]
Add the average complex amplitites and add to the image.
Parameters:
fftValues th earray of computed FFT values.
Definition at line 1204 of file WaterfallDisplay.java.
References opensonata.dataDisplays.WaterfallDisplay.FileScanner.plotComplexAmplitudes().
Referenced by opensonata.dataDisplays.WaterfallDisplay.FileScanner.run().
void opensonata.dataDisplays.WaterfallDisplay.FileScanner.plotComplexAmplitudes (double[] values) [private]
Add a line of complex amplitude averates to the image.
Parameters:
values the array of average values.
Definition at line 1221 of file WaterfallDisplay.java.
References opensonata.dataDisplays.WaterfallDisplay.FileScanner.clearPlot().
Referenced by opensonata.dataDisplays.WaterfallDisplay.FileScanner.plotAverageComplexAmplitudes().
void opensonata.dataDisplays.WaterfallDisplay.FileScanner.run ()
Run continually.
Definition at line 1310 of file WaterfallDisplay.java.
References opensonata.dataDisplays.WaterfallDisplay.FileScanner.addPixelRowToImage(), opensonata.dataDisplays.WaterfallDisplay.FileScanner.openFile(), opensonata.dataDisplays.WaterfallDisplay.FileScanner.plotAverageComplexAmplitudes(), opensonata.dataDisplays.WaterfallDisplay.FileScanner.saveWaterfallAsJpegFile(), opensonata.dataDisplays.WaterfallDisplay.FileScanner.sleep(), opensonata.dataDisplays.WaterfallDisplay.FileScanner.slowPlaySleep(), and opensonata.dataDisplays.WaterfallDisplay.FileScanner.updateDisplayHeaders().
void opensonata.dataDisplays.WaterfallDisplay.FileScanner.saveWaterfallAsJpegFile () throws java.io.IOException [private]
Save the waterfall image to a jpeg file.
Definition at line 1293 of file WaterfallDisplay.java.
Referenced by opensonata.dataDisplays.WaterfallDisplay.FileScanner.run().
void opensonata.dataDisplays.WaterfallDisplay.FileScanner.separatePreviouslyDisplayedData () [private]
Add a separator between the old data & the new. make the line just bright enough to see without being too bright.
Definition at line 1037 of file WaterfallDisplay.java.
References opensonata.dataDisplays.WaterfallDisplay.FileScanner.addRowsOfConstantBrightness().
Referenced by opensonata.dataDisplays.WaterfallDisplay.FileScanner.openFile().
void opensonata.dataDisplays.WaterfallDisplay.FileScanner.sleep () [private]
Sleep 200 milliseconds.
Definition at line 1020 of file WaterfallDisplay.java.
Referenced by opensonata.dataDisplays.WaterfallDisplay.FileScanner.run().
void opensonata.dataDisplays.WaterfallDisplay.FileScanner.slowPlaySleep () [private]
Sleep for 750 milliseconds.
Definition at line 1275 of file WaterfallDisplay.java.
Referenced by opensonata.dataDisplays.WaterfallDisplay.FileScanner.run().
void opensonata.dataDisplays.WaterfallDisplay.FileScanner.updateDisplayHeaders (ComplexAmplitudes compAmps) [private]
Update the GUI text information.
Parameters:
compAmps an instance of a ComplexAmplitudes class containing the information to display.
Definition at line 1102 of file WaterfallDisplay.java.
References opensonata.dataDisplays.WaterfallDisplay.FileScanner.addRowsOfConstantBrightness(), and opensonata.dataDisplays.WaterfallDisplay.ComplexAmplitudes.getPolAsString().
Referenced by opensonata.dataDisplays.WaterfallDisplay.FileScanner.run().
The documentation for this class was generated from the following file:
WaterfallDisplay.java