OpenSonATA Source Code Documentation
Back to setiCode Home
opensonata.dataDisplays.WaterfallDisplay Class Reference
Classes
class AverageComplexAmplitudes
class CoefConversion
class ComplexAmplitudes
class CustomFilenameFilter
class FileScanner
class ImagePanel
class OffsetSliderListener
class OpenFileListener
class PrintListener
class ReadoutBinNumberMouseListener
class ResolutionListener
class SaveAsJpegListener
class ScaleSliderListener
class SubbandOffsetListener
class WaterfallCmdLineOptions
Public Member Functions
WaterfallDisplay (boolean usingGui, JFrame mainGuiFrame, String inFilename, String outFilename, int subbandOffset, int width, int height, float pixelScaleFactor, float pixelOffsetFactor, int resolutionHz, boolean slowPlay, boolean repeatPlay, String title)
void scaleImage ()
void eraseImage ()
void redrawImage ()
void readoutData (ReadoutPlot source, double xPlotValue, double yPlotValue)
void init ()
Static Public Member Functions
static void main (String[] args)
Private Member Functions
void changeDisplayedFilename (String newname)
String getArchiveDir ()
double convertBinNumberToFreq (int binNumber, double rfCenterFrequency, double hzPerSubband)
void createImageAdjustmentControlPanel ()
void createCompAmpTimeAvgPlot ()
void setUpGui ()
Detailed Description
Reads complex amplitude time samples from a file and plots the data as freq vs time vs power.
Definition at line 67 of file WaterfallDisplay.java.
Constructor & Destructor Documentation
opensonata.dataDisplays.WaterfallDisplay.WaterfallDisplay (boolean usingGui, JFrame mainGuiFrame, String inFilename, String outFilename, int subbandOffset, int width, int height, float pixelScaleFactor, float pixelOffsetFactor, int resolutionHz, boolean slowPlay, boolean repeatPlay, String title)
Constructor.
Parameters:
usingGui true if using GUI, false if not.
mainGuiFrame the JFrame containing the GUI.
inFilename the input data file name.
outFilename the output data file name.
subbandOffset the subband offset.
width the width if the waterfall image window.
height the hieght if the waterfall image window.
pixelScaleFactor the waterfall image scale.
pixelOffsetFactor the waterfall image offset.
resolutionHz the resolution in Hz (1, 2 or 4)
slowPlay if true display the data slowly to approximate the speed of the real time system.
repeatPlay if true repeat over and over.
title the title to display at the top of the frame.
Definition at line 861 of file WaterfallDisplay.java.
References opensonata.dataDisplays.WaterfallDisplay.ComplexAmplitudes.setSubbandOffset().
Referenced by opensonata.dataDisplays.WaterfallDisplay.main().
Member Function Documentation
void opensonata.dataDisplays.WaterfallDisplay.changeDisplayedFilename (String newname) [private]
Change the display name text field.
Parameters:
newname the new file name to display.
Definition at line 1836 of file WaterfallDisplay.java.
Referenced by opensonata.dataDisplays.WaterfallDisplay.OpenFileListener.actionPerformed(), opensonata.dataDisplays.WaterfallDisplay.createCompAmpTimeAvgPlot(), and opensonata.dataDisplays.WaterfallDisplay.setUpGui().
double opensonata.dataDisplays.WaterfallDisplay.convertBinNumberToFreq (int binNumber, double rfCenterFrequency, double hzPerSubband) [private]
Convert the a bin number to its frequency.
Parameters:
binNumber the number of the bin.
rfCenterFrequency the center frequency of the data.
hzPerSubband hertz/subband for this data.
Returns:
the frequency of the bin.
Definition at line 1868 of file WaterfallDisplay.java.
Referenced by opensonata.dataDisplays.WaterfallDisplay.ReadoutBinNumberMouseListener.mouseMoved(), and opensonata.dataDisplays.WaterfallDisplay.readoutData().
void opensonata.dataDisplays.WaterfallDisplay.createCompAmpTimeAvgPlot () [private]
Create a complex amplitude time average plot in a JFrame.
Definition at line 2043 of file WaterfallDisplay.java.
References opensonata.dataDisplays.ReadoutPlot.addReadoutListener(), and opensonata.dataDisplays.WaterfallDisplay.changeDisplayedFilename().
Referenced by opensonata.dataDisplays.WaterfallDisplay.setUpGui().
void opensonata.dataDisplays.WaterfallDisplay.createImageAdjustmentControlPanel () [private]
Create the image adjustment control panel.
Definition at line 1999 of file WaterfallDisplay.java.
Referenced by opensonata.dataDisplays.WaterfallDisplay.setUpGui().
void opensonata.dataDisplays.WaterfallDisplay.eraseImage ()
Clear the image.
Definition at line 1469 of file WaterfallDisplay.java.
References opensonata.dataDisplays.WaterfallDisplay.redrawImage().
Referenced by opensonata.dataDisplays.WaterfallDisplay.setUpGui().
String opensonata.dataDisplays.WaterfallDisplay.getArchiveDir () [private]
Get the sse archive directory. If the SSE_ARCHIVE env var is set, use that, else use the default $HOME/sse_archive.
Returns:
the archive directory string.
Definition at line 1849 of file WaterfallDisplay.java.
References opensonata.dataDisplays.EnvReader.getEnvVar().
Referenced by opensonata.dataDisplays.WaterfallDisplay.setUpGui().
void opensonata.dataDisplays.WaterfallDisplay.init ()
Initialize the program.
Definition at line 2457 of file WaterfallDisplay.java.
References opensonata.dataDisplays.WaterfallDisplay.redrawImage(), and opensonata.dataDisplays.WaterfallDisplay.setUpGui().
Referenced by opensonata.dataDisplays.WaterfallDisplay.main().
static void opensonata.dataDisplays.WaterfallDisplay.main (String[] args) [static]
The main entry pont for the program.
Parameters:
args the command line arguments string array.
Definition at line 2836 of file WaterfallDisplay.java.
References opensonata.dataDisplays.WaterfallDisplay.WaterfallCmdLineOptions.getBatch(), opensonata.dataDisplays.WaterfallDisplay.WaterfallCmdLineOptions.getInFilename(), opensonata.dataDisplays.WaterfallDisplay.WaterfallCmdLineOptions.getOutFilename(), opensonata.dataDisplays.WaterfallDisplay.WaterfallCmdLineOptions.getRepeatPlay(), opensonata.dataDisplays.WaterfallDisplay.WaterfallCmdLineOptions.getResolutionHz(), opensonata.dataDisplays.WaterfallDisplay.WaterfallCmdLineOptions.getSlowPlay(), opensonata.dataDisplays.WaterfallDisplay.WaterfallCmdLineOptions.getSubbandOffset(), opensonata.dataDisplays.WaterfallDisplay.WaterfallCmdLineOptions.getTitle(), opensonata.dataDisplays.WaterfallDisplay.WaterfallCmdLineOptions.getXpos(), opensonata.dataDisplays.WaterfallDisplay.WaterfallCmdLineOptions.getYpos(), opensonata.dataDisplays.WaterfallDisplay.init(), opensonata.dataDisplays.WaterfallDisplay.WaterfallCmdLineOptions.parseCommandLineArgs(), and opensonata.dataDisplays.WaterfallDisplay.WaterfallDisplay().
void opensonata.dataDisplays.WaterfallDisplay.readoutData (ReadoutPlot source, double xPlotValue, double yPlotValue)
Calculate and display the aveCompAmpsBinFreqReadoutValueLabel, aveCompAmpsBinNumberReadoutValueLabel, and aveCompAmpsPowerReadoutValueLabel.
Parameters:
source the source ReadoutPlot instance.
xPlotValue the subband number.
yPlotValue the subband power.
Implements opensonata.dataDisplays.ReadoutListener.
Definition at line 1971 of file WaterfallDisplay.java.
References opensonata.dataDisplays.WaterfallDisplay.convertBinNumberToFreq().
void opensonata.dataDisplays.WaterfallDisplay.redrawImage ()
Redraw the image.
Definition at line 1485 of file WaterfallDisplay.java.
References opensonata.dataDisplays.WaterfallDisplay.scaleImage().
Referenced by opensonata.dataDisplays.WaterfallDisplay.FileScanner.addPixelRowToImage(), opensonata.dataDisplays.WaterfallDisplay.FileScanner.addRowsOfConstantBrightness(), opensonata.dataDisplays.WaterfallDisplay.eraseImage(), opensonata.dataDisplays.WaterfallDisplay.init(), opensonata.dataDisplays.WaterfallDisplay.ScaleSliderListener.stateChanged(), and opensonata.dataDisplays.WaterfallDisplay.OffsetSliderListener.stateChanged().
void opensonata.dataDisplays.WaterfallDisplay.scaleImage ()
Scale the image.
Definition at line 1459 of file WaterfallDisplay.java.
Referenced by opensonata.dataDisplays.WaterfallDisplay.redrawImage().
void opensonata.dataDisplays.WaterfallDisplay.setUpGui () [private]
Set up the GUI.
Handle the file scanner open file action.
Handle the file scanner open action.
param e the ActionEvent information for this action.
Handle the exit event.
Handle the exit.
param e the ActionEvent intance with information about this event.
Clear the display.
Handle the erase image action.
param e the ActionEvent instance with information about the event.
Display contrast/brightness panel
Handle the image adjustment action.
param e the ActionEvent information for this action.
Display Ave. Comp Amp Plot
Handle the average complex amplitude display action.
param e the ActionEvent information for this action.
Handle the Help Version action.
Handle the action that displays the help verion dialog.
param e the ActionEvent information for this action.
Definition at line 2123 of file WaterfallDisplay.java.
References opensonata.dataDisplays.WaterfallDisplay.changeDisplayedFilename(), opensonata.dataDisplays.WaterfallDisplay.createCompAmpTimeAvgPlot(), opensonata.dataDisplays.WaterfallDisplay.createImageAdjustmentControlPanel(), opensonata.dataDisplays.WaterfallDisplay.eraseImage(), opensonata.dataDisplays.WaterfallDisplay.getArchiveDir(), and opensonata.dataDisplays.WaterfallDisplay.ImagePanel.setImage().
Referenced by opensonata.dataDisplays.WaterfallDisplay.init().
The documentation for this class was generated from the following file:
WaterfallDisplay.java