OpenSonATA Source Code Documentation
Back to setiCode Home
opensonata.dataDisplays.BaselineDisplay.Baseline Class Reference
Public Member Functions
int getHeaderSizeBytes ()
int getBodySizeBytes ()
void read (DataInputStream in) throws java.io.IOException
void readHeader (DataInputStream in) throws java.io.IOException
void readBody (DataInputStream in) throws java.io.IOException
String getPolAsString ()
void printHeader ()
void printBody ()
Private Member Functions
String polIntToString (int pol)
Detailed Description
Manages the baseline data. See ssePdmInterface.h for C++ version of this struct (BaselineHeader and BaselineValue structs)
Definition at line 203 of file BaselineDisplay.java.
Member Function Documentation
int opensonata.dataDisplays.BaselineDisplay.Baseline.getBodySizeBytes ()
Get the size of one line of data.
Returns:
the data size in bytes.
Definition at line 236 of file BaselineDisplay.java.
int opensonata.dataDisplays.BaselineDisplay.Baseline.getHeaderSizeBytes ()
Get the size of the data header.
Returns:
the header size in bytes.
Definition at line 225 of file BaselineDisplay.java.
String opensonata.dataDisplays.BaselineDisplay.Baseline.getPolAsString ()
get the latest read in polarization from the header as a string.
Returns:
R, L, B, M, or ?
Definition at line 332 of file BaselineDisplay.java.
References opensonata.dataDisplays.BaselineDisplay.Baseline.polIntToString().
Referenced by opensonata.dataDisplays.BaselineDisplay.BaselineDataFileScanner.updateDisplayHeaders().
String opensonata.dataDisplays.BaselineDisplay.Baseline.polIntToString (int pol) [private]
Convert the polarization value in the header to a string.
Parameters:
pol the polarization number from the header.
Returns:
R, L, B, M, or ?
Definition at line 307 of file BaselineDisplay.java.
Referenced by opensonata.dataDisplays.BaselineDisplay.Baseline.getPolAsString(), and opensonata.dataDisplays.BaselineDisplay.Baseline.printHeader().
void opensonata.dataDisplays.BaselineDisplay.Baseline.printBody ()
Print to standard out the latest read in complex amplitude values.
Definition at line 355 of file BaselineDisplay.java.
void opensonata.dataDisplays.BaselineDisplay.Baseline.printHeader ()
Print to standard out the lastest read in header information.
Definition at line 340 of file BaselineDisplay.java.
References opensonata.dataDisplays.BaselineDisplay.Baseline.polIntToString().
void opensonata.dataDisplays.BaselineDisplay.Baseline.read (DataInputStream in) throws java.io.IOException
Read in one line of data. First the header, then the data body.
Parameters:
in the input data stream to read from.
Exceptions:
java.io.IOException.
Definition at line 250 of file BaselineDisplay.java.
References opensonata.dataDisplays.BaselineDisplay.Baseline.readBody(), and opensonata.dataDisplays.BaselineDisplay.Baseline.readHeader().
void opensonata.dataDisplays.BaselineDisplay.Baseline.readBody (DataInputStream in) throws java.io.IOException
Read the body of the data.
Parameters:
in the input data stream to read from.
Exceptions:
java.io.IOException.
Definition at line 280 of file BaselineDisplay.java.
Referenced by opensonata.dataDisplays.BaselineDisplay.Baseline.read().
void opensonata.dataDisplays.BaselineDisplay.Baseline.readHeader (DataInputStream in) throws java.io.IOException
Read the header.
Parameters:
in the input data stream to read from.
Exceptions:
java.io.IOException.
Definition at line 262 of file BaselineDisplay.java.
Referenced by opensonata.dataDisplays.BaselineDisplay.Baseline.read().
The documentation for this class was generated from the following file:
BaselineDisplay.java