OpenSonATA Source Code Documentation
Back to setiCode Home
opensonata.dataDisplays.EnvReader Class Reference
Public Member Functions
EnvReader ()
String getEnvVar (String envVarName)
Static Public Member Functions
static void main (String[] args) throws IOException
Private Member Functions
Map getEnvironment ()
Detailed Description
Reads in the environment variables.
Definition at line 53 of file EnvReader.java.
Constructor & Destructor Documentation
opensonata.dataDisplays.EnvReader.EnvReader ()
Constructor.
Definition at line 60 of file EnvReader.java.
References opensonata.dataDisplays.EnvReader.getEnvironment().
Referenced by opensonata.dataDisplays.EnvReader.main().
Member Function Documentation
Map opensonata.dataDisplays.EnvReader.getEnvironment () [private]
Read the environment variables into a HashMap.
Returns:
a hashMapp containing the varname:value as key:value pairs.
Definition at line 84 of file EnvReader.java.
Referenced by opensonata.dataDisplays.EnvReader.EnvReader().
String opensonata.dataDisplays.EnvReader.getEnvVar (String envVarName)
Get the value of an environment variable.
Parameters:
envVarName the name ov the environment variable.
Returns:
the string value of the environment variable, or null if it does not exist.
Definition at line 74 of file EnvReader.java.
Referenced by opensonata.dataDisplays.WaterfallDisplay.getArchiveDir(), opensonata.dataDisplays.BaselineDisplay.getArchiveDir(), and opensonata.dataDisplays.EnvReader.main().
static void opensonata.dataDisplays.EnvReader.main (String[] args) throws IOException [static]
The main entry point. Used mainly for testing. Prints out the environment varibale.
Parameters:
args the command line argument array.
Definition at line 135 of file EnvReader.java.
References opensonata.dataDisplays.EnvReader.EnvReader(), and opensonata.dataDisplays.EnvReader.getEnvVar().
The documentation for this class was generated from the following file:
EnvReader.java