OpenSonATA Source Code Documentation
Back to setiCode Home
opensonata.dataDisplays.BaselineDisplay.BaselineDataFileScanner Class Reference
Public Member Functions
void openNewFile (String filename)
void run ()
Package Functions
BaselineDataFileScanner (String filename, int width, int height)
Private Member Functions
void openFile ()
void sleep ()
void addPixelRowToImage (int[] pixrow)
void clearPlot ()
void updateDisplayHeaders (Baseline baseline)
void resetTimeAvg ()
void plotBaseline (Baseline baseline)
Detailed Description
Read a file containing gray pixel data and turn it into an image.
If an EOFException is received, it means the file has been truncated and it needs to be reopened.
Effectively does a 'tail -f' on the file, sleeping periodically until new data appears.
Definition at line 475 of file BaselineDisplay.java.
Constructor & Destructor Documentation
opensonata.dataDisplays.BaselineDisplay.BaselineDataFileScanner.BaselineDataFileScanner (String filename, int width, int height) [package]
Constructor.
Parameters:
filename the name of the file to read.
width the width of the image.
height the height of the image.
Definition at line 495 of file BaselineDisplay.java.
Member Function Documentation
void opensonata.dataDisplays.BaselineDisplay.BaselineDataFileScanner.addPixelRowToImage (int[] pixrow) [private]
Add the row of pixels to the top of the image.
Parameters:
pixrow an array of data to be added as one row of the image.
Definition at line 583 of file BaselineDisplay.java.
References opensonata.dataDisplays.BaselineDisplay.redrawImage().
void opensonata.dataDisplays.BaselineDisplay.BaselineDataFileScanner.clearPlot () [private]
Clear the plot.
Definition at line 601 of file BaselineDisplay.java.
Referenced by opensonata.dataDisplays.BaselineDisplay.BaselineDataFileScanner.openFile(), and opensonata.dataDisplays.BaselineDisplay.BaselineDataFileScanner.plotBaseline().
void opensonata.dataDisplays.BaselineDisplay.BaselineDataFileScanner.openFile () [private]
Open the file.
Definition at line 533 of file BaselineDisplay.java.
References opensonata.dataDisplays.BaselineDisplay.BaselineDataFileScanner.clearPlot(), and opensonata.dataDisplays.BaselineDisplay.BaselineDataFileScanner.resetTimeAvg().
Referenced by opensonata.dataDisplays.BaselineDisplay.BaselineDataFileScanner.openNewFile(), and opensonata.dataDisplays.BaselineDisplay.BaselineDataFileScanner.run().
void opensonata.dataDisplays.BaselineDisplay.BaselineDataFileScanner.openNewFile (String filename)
Assign the filename to this class instance and open the file.
Parameters:
filename the name of the file to open.
Definition at line 524 of file BaselineDisplay.java.
References opensonata.dataDisplays.BaselineDisplay.BaselineDataFileScanner.openFile().
void opensonata.dataDisplays.BaselineDisplay.BaselineDataFileScanner.plotBaseline (Baseline baseline) [private]
Calculate and plot the baseline.
Parameters:
baseline the Baseline instance to plot.
Definition at line 649 of file BaselineDisplay.java.
References opensonata.dataDisplays.BaselineDisplay.BaselineDataFileScanner.clearPlot().
Referenced by opensonata.dataDisplays.BaselineDisplay.BaselineDataFileScanner.run().
void opensonata.dataDisplays.BaselineDisplay.BaselineDataFileScanner.resetTimeAvg () [private]
Reset the time average to zeros.
Definition at line 633 of file BaselineDisplay.java.
Referenced by opensonata.dataDisplays.BaselineDisplay.BaselineDataFileScanner.openFile().
void opensonata.dataDisplays.BaselineDisplay.BaselineDataFileScanner.run ()
Run continually.
Todo:
Devise a better way to handle exceptions raised while reading and displaying the data.
Maybe reset file and start over?
Definition at line 698 of file BaselineDisplay.java.
References opensonata.dataDisplays.BaselineDisplay.BaselineDataFileScanner.openFile(), opensonata.dataDisplays.BaselineDisplay.BaselineDataFileScanner.plotBaseline(), opensonata.dataDisplays.BaselineDisplay.BaselineDataFileScanner.sleep(), and opensonata.dataDisplays.BaselineDisplay.BaselineDataFileScanner.updateDisplayHeaders().
void opensonata.dataDisplays.BaselineDisplay.BaselineDataFileScanner.sleep () [private]
Sleep 200 milliseconds.
Definition at line 558 of file BaselineDisplay.java.
Referenced by opensonata.dataDisplays.BaselineDisplay.BaselineDataFileScanner.run().
void opensonata.dataDisplays.BaselineDisplay.BaselineDataFileScanner.updateDisplayHeaders (Baseline baseline) [private]
Update the GUI text information based on the header information.
Parameters:
baseline the instance of the Baseline class containing the information to display.
Definition at line 613 of file BaselineDisplay.java.
References opensonata.dataDisplays.BaselineDisplay.Baseline.getPolAsString().
Referenced by opensonata.dataDisplays.BaselineDisplay.BaselineDataFileScanner.run().
The documentation for this class was generated from the following file:
BaselineDisplay.java