OpenSonATA Source Code Documentation
Back to setiCode Home
opensonata.dataDisplays.BaselineDisplay Class Reference
Classes
class Baseline
class BaselineCmdLineOptions
class BaselineDataFileScanner
class CustomFilenameFilter
class ImagePanel
class OffsetSliderListener
class OpenFileListener
class PrintListener
class SaveAsJpegListener
class ScaleSliderListener
Public Member Functions
BaselineDisplay (JFrame frame, String filename, int width, int height, float pixelScaleFactor, float pixelOffsetFactor, boolean slowPlay, boolean useTimeAvg)
void readoutData (ReadoutPlot source, double xPlotValue, double yPlotValue)
void scaleImage ()
void redrawImage ()
void init ()
Static Public Member Functions
static void main (String[] args)
Private Member Functions
double convertSubbandNumberToFreq (int subband)
void changeDisplayedFilename (String newname)
String getArchiveDir ()
Detailed Description
Read binary baselines (stored as C structs) on the input file and plot them. Structs & enums are defined in ssePdmInterface.h and sseInterface.h. Assumes the baseline structs are in network byte order.
Definition at line 68 of file BaselineDisplay.java.
Constructor & Destructor Documentation
opensonata.dataDisplays.BaselineDisplay.BaselineDisplay (JFrame frame, String filename, int width, int height, float pixelScaleFactor, float pixelOffsetFactor, boolean slowPlay, boolean useTimeAvg)
Constructor.
Parameters:
frame the JFrame containing the GUI.
filename the input data file name.
width the width if the waterfall image window.
height the hieght if the waterfall image window.
pixelScaleFactor the scale factor.
pixelOffsetFactor the pixel offset of the image.
slowPlay if true display the data slowly to approximate the speed of the real time system.
useTimeAvg if true display the average over time.
Definition at line 384 of file BaselineDisplay.java.
Referenced by opensonata.dataDisplays.BaselineDisplay.main().
Member Function Documentation
void opensonata.dataDisplays.BaselineDisplay.changeDisplayedFilename (String newname) [private]
Change the display name text field.
Parameters:
newname the new file name to display.
Definition at line 1070 of file BaselineDisplay.java.
Referenced by opensonata.dataDisplays.BaselineDisplay.OpenFileListener.actionPerformed(), and opensonata.dataDisplays.BaselineDisplay.init().
double opensonata.dataDisplays.BaselineDisplay.convertSubbandNumberToFreq (int subband) [private]
Convert a subband number to the frequency it represents.
Parameters:
subband the subband to convert.
Returns:
the frequency in MHz of the subband.
Definition at line 413 of file BaselineDisplay.java.
Referenced by opensonata.dataDisplays.BaselineDisplay.readoutData().
String opensonata.dataDisplays.BaselineDisplay.getArchiveDir () [private]
Get the sse archive directory. If the SSE_ARCHIVE env var is set, use that, else use the default $HOME/sse_archive.
Returns:
the archive directory string.
Definition at line 1083 of file BaselineDisplay.java.
References opensonata.dataDisplays.EnvReader.getEnvVar().
Referenced by opensonata.dataDisplays.BaselineDisplay.init().
void opensonata.dataDisplays.BaselineDisplay.init ()
Initialize the program.
Handle the file scanner open file action.
Handle the file scanner open action.
param e the ActionEvent information for this action.
Handle the exit event.
Handle the exit.
param e the ActionEvent intance with information about this event.
Handle the clear plot event.
Handle the clear plot.
param e the ActionEvent intance with information about this event.
Handle the rescale plot event.
Handle the rescale plot.
param e the ActionEvent intance with information about this event.
Handle the time average on/off event.
Handle the time average on/off.
param e the ItemEvent intance with information about this event.
Handle the Help Version action.
Handle the action that displays the help verion dialog.
param event the ActionEvent information for this action.
Definition at line 1097 of file BaselineDisplay.java.
References opensonata.dataDisplays.ReadoutPlot.addReadoutListener(), opensonata.dataDisplays.BaselineDisplay.changeDisplayedFilename(), opensonata.dataDisplays.BaselineDisplay.getArchiveDir(), opensonata.dataDisplays.BaselineDisplay.redrawImage(), and opensonata.dataDisplays.BaselineDisplay.ImagePanel.setImage().
static void opensonata.dataDisplays.BaselineDisplay.main (String[] args) [static]
The main entry pont for the program.
Parameters:
args the command line arguments string array.
Definition at line 1657 of file BaselineDisplay.java.
References opensonata.dataDisplays.BaselineDisplay.BaselineDisplay(), opensonata.dataDisplays.BaselineDisplay.BaselineCmdLineOptions.getFilename(), opensonata.dataDisplays.BaselineDisplay.BaselineCmdLineOptions.getHeight(), opensonata.dataDisplays.BaselineDisplay.BaselineCmdLineOptions.getSlowPlay(), opensonata.dataDisplays.BaselineDisplay.BaselineCmdLineOptions.getTimeAvg(), opensonata.dataDisplays.BaselineDisplay.BaselineCmdLineOptions.getWidth(), opensonata.dataDisplays.BaselineDisplay.BaselineCmdLineOptions.getXpos(), opensonata.dataDisplays.BaselineDisplay.BaselineCmdLineOptions.getYpos(), and opensonata.dataDisplays.BaselineDisplay.BaselineCmdLineOptions.parseCommandLineArgs().
void opensonata.dataDisplays.BaselineDisplay.readoutData (ReadoutPlot source, double xPlotValue, double yPlotValue)
Calculate and display the subbandFreqReadoutValueLabel, subbandNumberReadoutValueLabel, and subbandPowerReadoutValueLabel.
Parameters:
source the source ReadoutPlot instance.
xPlotValue the subband number.
yPlotValue the subband power.
Implements opensonata.dataDisplays.ReadoutListener.
Definition at line 440 of file BaselineDisplay.java.
References opensonata.dataDisplays.BaselineDisplay.convertSubbandNumberToFreq().
void opensonata.dataDisplays.BaselineDisplay.redrawImage ()
Redraw the image.
Definition at line 808 of file BaselineDisplay.java.
References opensonata.dataDisplays.BaselineDisplay.scaleImage().
Referenced by opensonata.dataDisplays.BaselineDisplay.BaselineDataFileScanner.addPixelRowToImage(), opensonata.dataDisplays.BaselineDisplay.init(), opensonata.dataDisplays.BaselineDisplay.ScaleSliderListener.stateChanged(), and opensonata.dataDisplays.BaselineDisplay.OffsetSliderListener.stateChanged().
void opensonata.dataDisplays.BaselineDisplay.scaleImage ()
Scale the image.
Definition at line 798 of file BaselineDisplay.java.
Referenced by opensonata.dataDisplays.BaselineDisplay.redrawImage().
The documentation for this class was generated from the following file:
BaselineDisplay.java