OpenSonATA: Screen Class Reference
Screen Class Reference
#include <screen.h>
Public Types
enum screen_modes_t {
screen_mode_components, screen_mode_signals, screen_mode_errors, screen_mode_summary,
screen_mode_last
}
Public Member Functions
Screen ()
~Screen ()
void init ()
void drawBottomMenu ()
void paint (Details *details)
void processKey (Details *details)
Static Public Member Functions
static void screenResize (int sig)
static void finish (int sig)
Private Attributes
int m_cols
int m_rows
bool m_isNewMode
int m_page
int m_curentPage
int m_totalPages
screen_modes_t m_screenMode
Static Private Attributes
static bool m_resizeEventOccurred = false
static int m_newCols = -1
static int m_newRows = -1
Detailed Description
Manages the curses screen.
Definition at line 54 of file screen.h.
Member Enumeration Documentation
enum Screen::screen_modes_t
Define the different type of screen modes. Currently there is only support for the components screen, but more are to be added later.
Definition at line 111 of file screen.h.
Constructor & Destructor Documentation
Screen::Screen ()
Constructor.
Definition at line 49 of file screen.cpp.
References finish(), and screenResize().
Screen::~Screen ()
Destructor.
Definition at line 68 of file screen.cpp.
Member Function Documentation
void Screen::drawBottomMenu ()
Draws the bottom of the screen. The Function keys.
Todo:
Multiple report screens need to be implemented. Until this is working the bottom menu should not be displayed.
Definition at line 158 of file screen.cpp.
Referenced by init(), paint(), and processKey().
void Screen::finish (int sig) [static]
Catch the control-c to quit screen mode then exit.
Parameters:
sig the signal.
Definition at line 149 of file screen.cpp.
Referenced by Screen().
void Screen::init ()
Initialize the curses screen.
Definition at line 75 of file screen.cpp.
References drawBottomMenu().
Referenced by main(), and paint().
void Screen::paint (Details * details)
paint the screen.
Parameters:
details the instance of the object containing the information to display on the screen.
Definition at line 209 of file screen.cpp.
References BOTTOM_MENU_HEIGHT, drawBottomMenu(), Details::getCurrentPageNumber(), Details::getNumPages(), Details::getType(), init(), Utils::itos(), and Details::paint().
Referenced by main(), and processKey().
void Screen::processKey (Details * details)
Process key presses.
Parameters:
details the Details object to redraw of a key affects the screen.
Todo:
Add multiple screens that change based on key presses.
Definition at line 276 of file screen.cpp.
References drawBottomMenu(), and paint().
Referenced by main().
void Screen::screenResize (int sig) [static]
Handles the screen rezise, which comes in as the result of a SIGWINCH signal. Executes the program "resize" to read in the terminal size.
Parameters:
sig the signal.
Definition at line 119 of file screen.cpp.
Referenced by main(), and Screen().
The documentation for this class was generated from the following files:
screen.h
screen.cpp