OpenSonATA: Utils Class Reference
Utils Class Reference
#include <utils.h>
Public Member Functions
Utils ()
~Utils ()
Static Public Member Functions
static string itos (unsigned long int num)
static string itos (unsigned int num)
static string itos (int num)
static string ftos (float num)
static float stof (string num)
static bool startsWith (string substring, string fullstring)
static void drawColorText (int y, int x, int color, string text)
static void drawSquare (int y, int x, int color)
Detailed Description
A class of general utilities.
Definition at line 50 of file utils.h.
Constructor & Destructor Documentation
Utils::Utils ()
The constructor.
Definition at line 41 of file utils.cpp.
Utils::~Utils ()
The destructor.
Definition at line 49 of file utils.cpp.
Member Function Documentation
void Utils::drawColorText (int y, int x, int color, string text) [static]
Draw text on the curses screen with a color.
Parameters:
y the y position on the screen.
x the x position on the screen.
color the color number. Depends on the screen setup.
text the text to display.
Definition at line 143 of file utils.cpp.
Referenced by Components::paint().
void Utils::drawSquare (int y, int x, int color) [static]
Draw one space in a color.
Parameters:
y the y position on the screen.
x the x position on the screen.
color the color number. Depends on the screen setup.
Definition at line 158 of file utils.cpp.
Referenced by Components::paint().
string Utils::ftos (float num) [static]
Convert a float to a string.
Parameters:
num the number to convert
Returns:
the resulting string
Definition at line 98 of file utils.cpp.
string Utils::itos (int num) [static]
Convert an integer to a string.
Parameters:
num the number to convert
Returns:
the resulting string
Definition at line 85 of file utils.cpp.
string Utils::itos (unsigned int num) [static]
Convert an unsigned integer to a string.
Parameters:
num the number to convert
Returns:
the resulting string
Definition at line 72 of file utils.cpp.
string Utils::itos (unsigned long int num) [static]
Convert an unsigned long integer to a string.
Parameters:
num the number to convert
Returns:
the resulting string
Definition at line 59 of file utils.cpp.
Referenced by Components::addWithFilter(), and Screen::paint().
bool Utils::startsWith (string substring, string fullstring) [static]
Test to see if a string starts with a string.
Parameters:
substring the sting to test for.
fullstring the string to search from the beginning.
Returns:
bool true if fullsting starts with substring.
Definition at line 127 of file utils.cpp.
Referenced by Components::addWithFilter().
float Utils::stof (string num) [static]
Convert a string to a float.
Parameters:
num the number string to convert.
Returns:
the resulting float
Definition at line 111 of file utils.cpp.
Referenced by Components::addWithFilter().
The documentation for this class was generated from the following files:
utils.h
utils.cpp