OpenSonATA: Details Class Reference
Details Class Reference
#include <details.h>
Public Types
enum detail_t {
detail_components, detail_signals, detail_errors, detail_summary,
detail_top, detail_bottom, detail_type_unknown
}
Public Member Functions
Details ()
~Details ()
void clear ()
void add (const string line)
void add (const string key, const string value)
bool exists (string key)
string getValue (string key)
std::pair< string, string > get (int i)
Details * getValueFromKeyStartsWith (string keyStart)
string toString (const string separator, const string lineEnd, int maxLineLength)
int getMaxKeyLength ()
int size ()
virtual bool addWithFilter (string line)
virtual int getNumPages (int pageRows)
virtual int getType ()
virtual int getCurrentPageNumber ()
virtual bool paint (int pageNum, int pageCols, int pageRows)
Public Attributes
detail_t m_thisType
Private Attributes
std::vector< std::pair< string,
string > > m_details
pthread_mutex_t m_mutex
Detailed Description
Manages status details. This is to be used as a base class.
Definition at line 50 of file details.h.
Constructor & Destructor Documentation
Details::Details ()
Constructor.
Definition at line 38 of file details.cpp.
References clear(), m_details, and m_mutex.
Referenced by getValueFromKeyStartsWith().
Details::~Details ()
Destructor.
Definition at line 46 of file details.cpp.
References clear(), and m_mutex.
Member Function Documentation
void Details::add (const string key, const string value)
Add a detail key::value to the list.
Parameters:
key the detail key.
value the detail value.
Definition at line 136 of file details.cpp.
References m_details, and m_mutex.
void Details::add (const string line)
Add a detail line to the list. A detail line is comprised of key<space>value.
Parameters:
line the detail line.
Definition at line 68 of file details.cpp.
References m_details, and m_mutex.
Referenced by Components::addWithFilter(), and getValueFromKeyStartsWith().
virtual bool Details::addWithFilter (string line) [inline, virtual]
Add a line of information about a component to the list.
Parameters:
line The line of text parse and add to the details list.
Returns:
true if an entire record has been read in and is ready for display on the screen.
Reimplemented in Components.
Definition at line 145 of file details.h.
void Details::clear ()
Empty the m_details vector.
Definition at line 55 of file details.cpp.
References m_details, and m_mutex.
Referenced by Components::addWithFilter(), Details(), and ~Details().
bool Details::exists (string key)
Test if a value exists by testing the key.
Parameters:
key the key.
Returns:
true if there is a value for this key.
Definition at line 157 of file details.cpp.
References m_details, and m_mutex.
std::pair< string, string > Details::get (int i)
Get a key:value pair from the list base of the index in the list.
Parameters:
i the index into the list.
Returns:
the key:value pair. Will be "null":"null" if the index is invalid.
Definition at line 273 of file details.cpp.
References m_details.
Referenced by Components::paint().
virtual int Details::getCurrentPageNumber () [inline, virtual]
Get the current page number displayed.
Returns:
the current page number displayed.
Reimplemented in Components.
Definition at line 168 of file details.h.
Referenced by Screen::paint().
int Details::getMaxKeyLength ()
Get the character length of the longest key in the list.
Returns:
the character length of the longest key in the list.
Definition at line 291 of file details.cpp.
References m_details.
virtual int Details::getNumPages (int pageRows) [inline, virtual]
Get the number of pages required to display all the information.
Parameters:
pageRows the number of rows available on the screen.
Returns:
the number of pages required to display all the information.
Reimplemented in Components.
Definition at line 154 of file details.h.
Referenced by Screen::paint().
virtual int Details::getType () [inline, virtual]
Get the type of this object inherited from the Details class.
Returns:
the type as a detail_t enum value.
Reimplemented in Components.
Definition at line 161 of file details.h.
Referenced by Screen::paint().
string Details::getValue (string key)
Get the value for a key.
Parameters:
key the key.
Returns:
the value for the key, or empty string if it does not exist.
Definition at line 186 of file details.cpp.
References m_details, and m_mutex.
Details * Details::getValueFromKeyStartsWith (string keyStart)
Get all values that have a key that starts with a character substring.
Parameters:
keyStart the substring to match with the keys.
Returns:
a Details object filled with the key:value pairs.
Definition at line 212 of file details.cpp.
References add(), Details(), and m_details.
virtual bool Details::paint (int pageNum, int pageCols, int pageRows) [inline, virtual]
Display the information on the screen.
Parameters:
pageNum the page number to display.
pageCols the number of columns on the screen.
pageRows the number of rows on the screen.
Returns:
true if screen has changed, else false.
Reimplemented in Components.
Definition at line 178 of file details.h.
Referenced by Screen::paint().
int Details::size ()
Get the number of key:value pairs in the list.
Definition at line 174 of file details.cpp.
References m_details.
Referenced by Components::addWithFilter(), and Components::paint().
string Details::toString (const string separator, const string lineEnd, int maxLineLength)
Convert the key:value pairs into one string, keach key value separated by a line ending.
Parameters:
separator the separator to place between the key and the value.
lineEnd the character(s) to use as a line ending. Usually
.
maxLineLength the maximum length of a line.
Returns:
the resulting multi line string.
Definition at line 243 of file details.cpp.
References m_details.
Member Data Documentation
std::vector<std::pair<string, string> > Details::m_details [private]
The std::vector that holds the key:value pairs. The key is the component such as "chan1x" or "dx1000", The value is the full status line.
Definition at line 200 of file details.h.
Referenced by add(), clear(), Details(), exists(), get(), getMaxKeyLength(), getValue(), getValueFromKeyStartsWith(), size(), and toString().
pthread_mutex_t Details::m_mutex [private]
The mutex that makes this class thread safe.
Definition at line 203 of file details.h.
Referenced by add(), clear(), Details(), exists(), getValue(), and ~Details().
The documentation for this class was generated from the following files:
details.h
details.cpp