OpenSonATA: Components Class Reference
Components Class Reference
#include <components.h>
Public Member Functions
Components ()
bool addWithFilter (string line)
int getNumPages (int pageRows)
int getType ()
int getCurrentPageNumber ()
bool paint (int pageNum, int pageCols, int pageRows)
Private Attributes
int m_lastRequestedPage
int m_lastReportedCols
int m_lastReportedRows
string m_time
string m_date
string m_activity
string m_fullPage [2]
int m_fullPageIndex
string m_currentPageBuffer
int m_pageCount
std::vector< string > m_screenBuffer
int m_chanTotalCount
int m_chanRunningCount
int m_dxOfflineCount
int m_dxIdleCount
int m_dxBaseAccumCount
int m_dxDataCollCount
int m_dxSigDetCount
int m_dxTotalCount
float m_minDxFreqMHz
float m_maxDxFreqMHz
int m_detailsCount
string m_channelizerSummary
string m_dxSummary
int m_lastFreqRangeStringLen
Detailed Description
Manages status details about system components such as dx's, channelizers, etc.. Inherits from the Details class.
Definition at line 47 of file components.h.
Constructor & Destructor Documentation
Components::Components ()
Constructor.
Definition at line 45 of file components.cpp.
Member Function Documentation
bool Components::addWithFilter (string line) [virtual]
Add a line of information about a component to the list. The information is filtered to accept only lines that start with channelizer, dx, arch, tscope, beam, array, primary, and NSS.
Parameters:
line The line of text read in from the "sse-system-status.txt" file.
Returns:
true if an entire record of system statuses have been read int. The end of a record is marked in "sse-system-status.txt" by a line starting with "=============". Else, false.
Reimplemented from Details.
Definition at line 95 of file components.cpp.
References Details::add(), Details::clear(), Utils::itos(), Details::size(), Utils::startsWith(), and Utils::stof().
Referenced by main().
int Components::getCurrentPageNumber () [virtual]
Get the current page number displayed.
Returns:
the current page number displayed.
Reimplemented from Details.
Definition at line 416 of file components.cpp.
int Components::getNumPages (int pageRows) [virtual]
Get the number of pages required to display all the information.
Parameters:
pageRows the number of rows available on the screen.
Returns:
the number of pages required to display all the information.
Reimplemented from Details.
Definition at line 392 of file components.cpp.
Referenced by paint().
int Components::getType () [virtual]
Get the type of this object inherited from the Details class.
Returns:
the type as a detail_t enum value.
Reimplemented from Details.
Definition at line 406 of file components.cpp.
bool Components::paint (int pageNum, int pageCols, int pageRows) [virtual]
Display the information on the screen.
Parameters:
pageNum the page number to display.
pageCols the number of columns on the screen.
pageRows the number of rows on the screen.
Returns:
true if screen has changed, else false.
Reimplemented from Details.
Definition at line 271 of file components.cpp.
References Utils::drawColorText(), Utils::drawSquare(), Details::get(), getNumPages(), and Details::size().
The documentation for this class was generated from the following files:
components.h
components.cpp