all: dataDisplays sonataInfoDisplay

dataDisplays:
	cd sse-pkg/dataDisplays; make;

sonataInfoDisplay:
	cd sse-pkg/util/sonataInfoDisplay; make;

clean:	
	cd sse-pkg/dataDisplays; make clean;
	cd sse-pkg/util/sonataInfoDisplay; make clean;
